name: Verify Dialyzer

on: pull_request

jobs:

  dialyzer:

    continue-on-error: false

    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.15.4]
        otp: [26]

    steps:

      - uses: actions/checkout@v2

      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v1
        id: mix-cache-dialyzer
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install Mix Dependencies
        if: steps.mix-cache-dialyzer.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Run Dialyzer
        run: mix dialyzer
        id: dialyzer

      - name: Check Dialyzer Result
        if: steps.dialyzer.outcome != 'success'
        run: exit 1
