name: Verify Format

on: pull_request

jobs:

  check_format:

    continue-on-error: false

    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.15.4]
        otp: [26]

    steps:

      - uses: actions/checkout@v2

      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v1
        id: mix-cache-format
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install Mix Dependencies
        if: steps.mix-cache-format.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Check Formatting
        run: mix format --check-formatted
        id: format

      - name: Check Format Result
        if: steps.format.outcome != 'success'
        run: |
          echo "Files not properly formatted!"
          exit 1
